# Generated by Django 4.1.8 on 2025-09-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='divisions/'),
        ),
    ]
